version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=Movies
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    ports:
      - "5432:5432"


  web:
    build: . 
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/movies
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=Movies
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - IMDB_KEY=4c56463f39mshc83a0842d95dcf2p1a7364jsn1f41a82a0394
    depends_on:
      - db

