# Generated by Django 4.0.2 on 2022-02-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='movie_genre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='movie_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='movie_year',
            field=models.CharField(max_length=255),
        ),
    ]
