# Generated by Django 4.0.2 on 2022-02-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_moviemodel_movie_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='movie_image',
            field=models.ImageField(blank=True, max_length=500, upload_to='uploads'),
        ),
    ]
